version: "3.7"

networks:
        proxy-net:
                name: ${PROXY_NET}
                external: true
        default-net:
                name: ${DEFAULT_NET}
                internal: true
        default-ext-net:
                name: ${DEFAULT_EXT_NET}
                external: true

services:
  thegame-service-prod:
    image: nginx
    container_name: thegame
    volumes:
      - ./client/vue/:/usr/share/nginx/html
      - ./client/vue/thegame.template:/etc/nginx/conf.d/thegame.template
    ports:
      - "9200:80"
    environment:
      NGINX_PORT: 80
      SERVER_ENVIRONMENT: PRODUCTION
      API_CONTAINER: thegame-api
    depends_on:
      - "thegame-api-service-prod"
    networks:
      - proxy-net
      - default-net
      - default-ext-net
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/thegame.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  thegame-api-service-prod:
    build:
      context: server
      dockerfile: prod.Dockerfile
    container_name: thegame-api
    depends_on:
      - "thegame-db-service-prod"
    ports:
      - "9201:9201"
    networks:
      - proxy-net
      - default-net
      - default-ext-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      SERVER_ENVIRONMENT: PRODUCTION
      DB_CONTAINER: thegame-db

  thegame-db-service-prod:
    image: mongo:latest
    container_name: thegame-db
    ports:
      - "27017:27017"
    networks:
      - proxy-net
      - default-net
      - default-ext-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      SERVER_ENVIRONMENT: PRODUCTION